# Generated by Django 5.0.6 on 2024-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='fooditems',
            options={'verbose_name': 'FoodItem', 'verbose_name_plural': 'FoodItems'},
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='food_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
